.DEFAULT_GOAL := test

.PHONY: clean docs help quality local-requirements requirements test validate coverage

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  clean                      delete generated byte code and coverage reports"
	@echo "  docs                       generate Sphinx documentation"
	@echo "  help                       display this help message"
	@echo "  coverage                   generate and view HTML coverage report"
	@echo "  quality                    run PEP8 and Pylint"
	@echo "  requirements               install requirements for local development"
	@echo "  test                       run tests and generate coverage report"
	@echo "  validate                   run tests and quality checks"
	@echo ""

clean:
	find . -name '*.pyc' -delete
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

docs:
	doc8 --ignore-path docs/_build README.rst docs
	rm -f docs/edx_salesforce.rst
	rm -f docs/modules.rst
	make -C docs clean
	make -C docs html
	python setup.py check --restructuredtext --strict

local-requirements:
	pip install -qr requirements/local.txt --exists-action w

requirements:
	pip install -qr requirements.txt --exists-action w

test: clean
	coverage run ./manage.py test edx_salesforce --settings=settings.test
	coverage report

quality:
	pep8 --config=.pep8 edx_salesforce *.py
	pylint --rcfile=pylintrc edx_salesforce *.py

validate: test quality

coverage:
	coverage html
