# -*- coding: utf-8 -*-
"""Choices for model fields."""

from __future__ import unicode_literals


COUNTRIES = [
    ('United States of America US', 'United States of America US'),
    ('Afghanistan AF', 'Afghanistan AF'),
    ('Åland Islands AX', 'Åland Islands AX'),
    ('Albania AL', 'Albania AL'),
    ('Algeria DZ', 'Algeria DZ'),
    ('American Samoa AS', 'American Samoa AS'),
    ('Andorra AD', 'Andorra AD'),
    ('Angola AO', 'Angola AO'),
    ('Anguilla AI', 'Anguilla AI'),
    ('Antarctica AQ', 'Antarctica AQ'),
    ('Antigua and Barbuda AG', 'Antigua and Barbuda AG'),
    ('Argentina AR', 'Argentina AR'),
    ('Armenia AM', 'Armenia AM'),
    ('Aruba AW', 'Aruba AW'),
    ('Australia AU', 'Australia AU'),
    ('Austria AT', 'Austria AT'), ('Azerbaijan AZ', 'Azerbaijan AZ'),
    ('Bahamas BS', 'Bahamas BS'), ('Bahrain BH', 'Bahrain BH'),
    ('Bangladesh BD', 'Bangladesh BD'), ('Barbados BB', 'Barbados BB'),
    ('Belarus BY', 'Belarus BY'), ('Belgium BE', 'Belgium BE'),
    ('Belize BZ', 'Belize BZ'), ('Benin BJ', 'Benin BJ'),
    ('Bermuda BM', 'Bermuda BM'), ('Bhutan BT', 'Bhutan BT'),
    ('Bolivia BO', 'Bolivia BO'), ('Bonaire', 'Bonaire'),
    ('Sint Eustatius and Saba BQ', 'Sint Eustatius and Saba BQ'),
    ('Bosnia and Herzegovina BA', 'Bosnia and Herzegovina BA'),
    ('Botswana BW', 'Botswana BW'), ('Bouvet Island BV', 'Bouvet Island BV'),
    ('Brazil BR', 'Brazil BR'),
    ('British Indian Ocean Territory IO', 'British Indian Ocean Territory IO'),
    ('Brunei BN', 'Brunei BN'), ('Bulgaria BG', 'Bulgaria BG'),
    ('Burkina Faso BF', 'Burkina Faso BF'), ('Burundi BI', 'Burundi BI'),
    ('Cabo Verde CV', 'Cabo Verde CV'), ('Cambodia KH', 'Cambodia KH'),
    ('Cameroon CM', 'Cameroon CM'), ('Canada CA', 'Canada CA'),
    ('Cayman Islands KY', 'Cayman Islands KY'),
    ('Central African Republic CF', 'Central African Republic CF'),
    ('Chad TD', 'Chad TD'), ('Chile CL', 'Chile CL'), ('China CN', 'China CN'),
    ('Christmas Island CX', 'Christmas Island CX'),
    ('Cocos (Keeling) Islands CC', 'Cocos (Keeling) Islands CC'),
    ('Colombia CO', 'Colombia CO'), ('Comoros KM', 'Comoros KM'),
    ('Congo CG', 'Congo CG'),
    ('Congo (the Democratic Republic of the) CD', 'Congo (the Democratic Republic of the) CD'),
    ('Cook Islands CK', 'Cook Islands CK'), ('Costa Rica CR', 'Costa Rica CR'),
    ("Cote d'Ivoire CI", "Cote d'Ivoire CI"), ('Croatia HR', 'Croatia HR'),
    ('Cuba CU', 'Cuba CU'), ('Curacao CW', 'Curacao CW'),
    ('Cyprus CY', 'Cyprus CY'), ('Czech Republic CZ', 'Czech Republic CZ'),
    ('Denmark DK', 'Denmark DK'), ('Djibouti DJ', 'Djibouti DJ'),
    ('Dominica DM', 'Dominica DM'),
    ('Dominican Republic DO', 'Dominican Republic DO'),
    ('Ecuador EC', 'Ecuador EC'), ('Egypt EG', 'Egypt EG'),
    ('El Salvador SV', 'El Salvador SV'),
    ('Equatorial Guinea GQ', 'Equatorial Guinea GQ'),
    ('Eritrea ER', 'Eritrea ER'), ('Estonia EE', 'Estonia EE'),
    ('Ethiopia ET', 'Ethiopia ET'),
    ('Falkland Islands [Malvinas] FK', 'Falkland Islands [Malvinas] FK'),
    ('Faroe Islands FO', 'Faroe Islands FO'), ('Fiji FJ', 'Fiji FJ'),
    ('Finland FI', 'Finland FI'), ('France FR', 'France FR'),
    ('French Guiana GF', 'French Guiana GF'),
    ('French Polynesia PF', 'French Polynesia PF'),
    ('French Southern Territories TF', 'French Southern Territories TF'),
    ('Gabon GA', 'Gabon GA'), ('Gambia GM', 'Gambia GM'),
    ('Georgia GE', 'Georgia GE'), ('Germany DE', 'Germany DE'),
    ('Ghana GH', 'Ghana GH'), ('Gibraltar GI', 'Gibraltar GI'),
    ('Greece GR', 'Greece GR'), ('Greenland GL', 'Greenland GL'),
    ('Grenada GD', 'Grenada GD'), ('Guadeloupe GP', 'Guadeloupe GP'),
    ('Guam GU', 'Guam GU'), ('Guatemala GT', 'Guatemala GT'),
    ('Guernsey GG', 'Guernsey GG'), ('Guinea GN', 'Guinea GN'),
    ('Guinea-Bissau GW', 'Guinea-Bissau GW'), ('Guyana GY', 'Guyana GY'),
    ('Haiti HT', 'Haiti HT'),
    ('Heard Island and McDonald Islands HM', 'Heard Island and McDonald Islands HM'),
    ('Holy See VA', 'Holy See VA'), ('Honduras HN', 'Honduras HN'),
    ('Hong Kong HK', 'Hong Kong HK'), ('Hungary HU', 'Hungary HU'),
    ('Iceland IS', 'Iceland IS'), ('India IN', 'India IN'),
    ('Indonesia ID', 'Indonesia ID'), ('Iran IR', 'Iran IR'),
    ('Iraq IQ', 'Iraq IQ'), ('Ireland IE', 'Ireland IE'),
    ('Isle of Man IM', 'Isle of Man IM'), ('Israel IL', 'Israel IL'),
    ('Italy IT', 'Italy IT'), ('Jamaica JM', 'Jamaica JM'),
    ('Japan JP', 'Japan JP'), ('Jersey JE', 'Jersey JE'),
    ('Jordan JO', 'Jordan JO'), ('Kazakhstan KZ', 'Kazakhstan KZ'),
    ('Kenya KE', 'Kenya KE'), ('Kiribati KI', 'Kiribati KI'),
    ('Kosovo XK', 'Kosovo XK'), ('Kuwait KW', 'Kuwait KW'),
    ('Kyrgyzstan KG', 'Kyrgyzstan KG'), ('Laos LA', 'Laos LA'),
    ('Latvia LV', 'Latvia LV'), ('Lebanon LB', 'Lebanon LB'),
    ('Lesotho LS', 'Lesotho LS'), ('Liberia LR', 'Liberia LR'),
    ('Libya LY', 'Libya LY'), ('Liechtenstein LI', 'Liechtenstein LI'),
    ('Lithuania LT', 'Lithuania LT'), ('Luxembourg LU', 'Luxembourg LU'),
    ('Macao MO', 'Macao MO'), ('Macedonia MK', 'Macedonia MK'),
    ('Madagascar MG', 'Madagascar MG'), ('Malawi MW', 'Malawi MW'),
    ('Malaysia MY', 'Malaysia MY'), ('Maldives MV', 'Maldives MV'),
    ('Mali ML', 'Mali ML'), ('Malta MT', 'Malta MT'),
    ('Marshall Islands MH', 'Marshall Islands MH'),
    ('Martinique MQ', 'Martinique MQ'), ('Mauritania MR', 'Mauritania MR'),
    ('Mauritius MU', 'Mauritius MU'), ('Mayotte YT', 'Mayotte YT'),
    ('Mexico MX', 'Mexico MX'),
    ('Micronesia (Federated States of) FM', 'Micronesia (Federated States of) FM'),
    ('Moldovia MD', 'Moldovia MD'), ('Monaco MC', 'Monaco MC'),
    ('Mongolia MN', 'Mongolia MN'), ('Montenegro ME', 'Montenegro ME'),
    ('Montserrat MS', 'Montserrat MS'), ('Morocco MA', 'Morocco MA'),
    ('Mozambique MZ', 'Mozambique MZ'), ('Myanmar MM', 'Myanmar MM'),
    ('Namibia NA', 'Namibia NA'), ('Nauru NR', 'Nauru NR'),
    ('Nepal NP', 'Nepal NP'), ('Netherlands NL', 'Netherlands NL'),
    ('New Caledonia NC', 'New Caledonia NC'),
    ('New Zealand NZ', 'New Zealand NZ'), ('Nicaragua NI', 'Nicaragua NI'),
    ('Niger NE', 'Niger NE'), ('Nigeria NG', 'Nigeria NG'),
    ('Niue NU', 'Niue NU'), ('Norfolk Island NF', 'Norfolk Island NF'),
    ('North Korea KP', 'North Korea KP'),
    ('Northern Mariana Islands MP', 'Northern Mariana Islands MP'),
    ('Norway NO', 'Norway NO'), ('Oman OM', 'Oman OM'),
    ('Pakistan PK', 'Pakistan PK'), ('Palau PW', 'Palau PW'),
    ('Palestine State of PS', 'Palestine State of PS'),
    ('Panama PA', 'Panama PA'), ('Papua New Guinea PG', 'Papua New Guinea PG'),
    ('Paraguay PY', 'Paraguay PY'), ('Peru PE', 'Peru PE'),
    ('Philippines PH', 'Philippines PH'), ('Pitcairn PN', 'Pitcairn PN'),
    ('Poland PL', 'Poland PL'), ('Portugal PT', 'Portugal PT'),
    ('Puerto Rico PR', 'Puerto Rico PR'), ('Qatar QA', 'Qatar QA'),
    ('Reunion RE', 'Reunion RE'), ('Romania RO', 'Romania RO'),
    ('Russia RU', 'Russia RU'), ('Rwanda RW', 'Rwanda RW'),
    ('Saint Bartholemy BL', 'Saint Bartholemy BL'),
    ('Saint Helena', 'Saint Helena'),
    ('Ascension and Tristan da Cunha SH', 'Ascension and Tristan da Cunha SH'),
    ('Saint Kitts and Nevis KN', 'Saint Kitts and Nevis KN'),
    ('Saint Lucia LC', 'Saint Lucia LC'),
    ('Saint Martin (French part) MF', 'Saint Martin (French part) MF'),
    ('Saint Pierre and Miquelon PM', 'Saint Pierre and Miquelon PM'),
    ('Saint Vincent and the Grenadines VC', 'Saint Vincent and the Grenadines VC'),
    ('Samoa WS', 'Samoa WS'), ('San Marino SM', 'San Marino SM'),
    ('Sao Tome and Principe ST', 'Sao Tome and Principe ST'),
    ('Saudi Arabia SA', 'Saudi Arabia SA'), ('Senegal SN', 'Senegal SN'),
    ('Serbia RS', 'Serbia RS'), ('Seychelles SC', 'Seychelles SC'),
    ('Sierra Leone SL', 'Sierra Leone SL'), ('Singapore SG', 'Singapore SG'),
    ('Saint Maarten (Dutch part) SX', 'Saint Maarten (Dutch part) SX'),
    ('Slovakia SK', 'Slovakia SK'), ('Slovenia SI', 'Slovenia SI'),
    ('Solomon Islands SB', 'Solomon Islands SB'), ('Somalia SO', 'Somalia SO'),
    ('South Africa ZA', 'South Africa ZA'),
    ('South Georgia and the South Sandwich Islands GS', 'South Georgia and the South Sandwich Islands GS'),
    ('South Korea KR', 'South Korea KR'), ('South Sudan SS', 'South Sudan SS'),
    ('Spain ES', 'Spain ES'), ('Sri Lanka LK', 'Sri Lanka LK'),
    ('Sudan SD', 'Sudan SD'), ('Suriname SR', 'Suriname SR'),
    ('Svalbard and Jan Mayen SJ', 'Svalbard and Jan Mayen SJ'),
    ('Swaziland SZ', 'Swaziland SZ'), ('Sweden SE', 'Sweden SE'),
    ('Switzerland CH', 'Switzerland CH'), ('Syria SY', 'Syria SY'),
    ('Taiwan TW', 'Taiwan TW'), ('Tajikistan TJ', 'Tajikistan TJ'),
    ('Tanzania TZ', 'Tanzania TZ'), ('Thailand TH', 'Thailand TH'),
    ('Timor-Leste TL', 'Timor-Leste TL'), ('Togo TG', 'Togo TG'),
    ('Tokelau TK', 'Tokelau TK'), ('Tonga TO', 'Tonga TO'),
    ('Trinidad and Tobago TT', 'Trinidad and Tobago TT'),
    ('Tunisia TN', 'Tunisia TN'), ('Turkey TR', 'Turkey TR'),
    ('Turkmenistan TM', 'Turkmenistan TM'),
    ('Turks and Caicos Islands TC', 'Turks and Caicos Islands TC'),
    ('Tuvalu TV', 'Tuvalu TV'), ('Uganda UG', 'Uganda UG'),
    ('Ukraine UA', 'Ukraine UA'),
    ('United Arab Emirates AE', 'United Arab Emirates AE'),
    ('United Kingdom of Great Britain and Northern Ireland GB',
     'United Kingdom of Great Britain and Northern Ireland GB'),
    ('United States Minor Outlying Islands UM', 'United States Minor Outlying Islands UM'),
    ('Uruguay UY', 'Uruguay UY'),
    ('Uzbekistan UZ', 'Uzbekistan UZ'), ('Vanuatu VU', 'Vanuatu VU'),
    ('Venezuela VE', 'Venezuela VE'), ('Vietnam VN', 'Vietnam VN'),
    ('Virgin Islands (British) VG', 'Virgin Islands (British) VG'),
    ('Virgin Islands (U.S.) VI', 'Virgin Islands (U.S.) VI'),
    ('Wallis and Futuna WF', 'Wallis and Futuna WF'),
    ('Western Sahara EH', 'Western Sahara EH'), ('Yemen YE', 'Yemen YE'),
    ('Zambia ZM', 'Zambia ZM'), ('Zimbabwe ZW', 'Zimbabwe ZW')
]

COUNTRIES_BY_CODE = {c[0][-2:]: c[0] for c in COUNTRIES}

EDUCATION = [
    ('p', 'Doctorate'),
    ('m', 'Master\'s or professional degree'),
    ('b', 'Bachelor\'s degree'),
    ('a', 'Associate degree'),
    ('hs', 'Secondary/high school'),
    ('jhs', 'Junior secondary/junior high/middle school'),
    ('el', 'Elementary/primary school'),
    ('none', 'No formal education'),
    ('other', 'Other education'),
]

EDUCATION_BY_CODE = {key: value for key, value in EDUCATION}
